---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r loadingData, echo=TRUE}
# loading data
if (!file.exists("activity.csv")) { unzip("activity.zip") }
activity <- read.csv("activity.csv")

# preprocessing data
activity$date <- as.Date(activity$date, "%Y-%m-%d")
```

## What is mean total number of steps taken per day?

```{r meanTotSteps, echo=TRUE}
daySteps <- tapply(activity$steps, activity$date, sum, na.rm = TRUE)
hist(daySteps, breaks = 10, main = "", xlab = "Steps taken per day")
mean(daySteps)
median(daySteps)
```

## What is the average daily activity pattern?

```{r averageDailyActivity, echo=TRUE}
library(dplyr)
meanIntSteps <- activity %>% group_by(interval) %>% summarise(meanSteps = mean(steps, na.rm = TRUE))
plot(meanIntSteps, type = 'l', ylab = "Average steps", xlab = "Time interval")
meanIntSteps$interval[which.max(meanIntSteps$meanSteps)]
```

## Imputing missing values

```{r}
#total number of rows with missing values
sum(is.na(activity$steps))

# fill in NAs with 0, need to do this better later
correctedActivity <- activity
for (i in seq_along(correctedActivity$steps))
{
    if (is.na(correctedActivity$steps[i]))
    {
        correctedActivity$steps[i] <- 0
    }
}

correctedDaySteps <- correctedActivity %>% group_by(date) %>% summarise(totalSteps = sum(steps))
hist(correctedDaySteps$totalSteps, breaks = 10, main = "", xlab = "Total steps taken per day")

mean(correctedDaySteps$totalSteps)
median(correctedDaySteps$totalSteps)
```

## Are there differences in activity patterns between weekdays and weekends?
